dynamic matrix

diff --git a/.github/workflows/dh.yml b/.github/workflows/dh.yml
--- a/.github/workflows/dh.yml
+++ b/.github/workflows/dh.yml
@@ -43,17 +43,17 @@ jobs:
           for i in app1 app2 app3; do
             echo "temp doing i: $i"
             echo "doing i: $i"
-            output=$(grep "$i" ${HOME}/files.json || echo "missing")
-            echo "output: $output"
-            if [ "$output" != "missing" ]; then
-              if [ "$i" == "app1" ]; then
-                matrixStringifiedObject="${matrixStringifiedObject}'{"build-dir":"app1","app-dir":"app/"},'
-              elif [ "$i" == "app2" ]; then
-                matrixStringifiedObject="${matrixStringifiedObject}'{"build-dir":"app2","app-dir":"app/"},'
-              elif [ "$i" == "app2" ]; then
-                matrixStringifiedObject="${matrixStringifiedObject}'{"build-dir":"app3","app-dir":""},'
-              fi
-            fi
+            #output=$(grep "$i" ${HOME}/files.json || echo "missing")
+            #echo "output: $output"
+            #if [ "$output" != "missing" ]; then
+            #  if [ "$i" == "app1" ]; then
+            #    matrixStringifiedObject="${matrixStringifiedObject}'{"build-dir":"app1","app-dir":"app/"},'
+            #  elif [ "$i" == "app2" ]; then
+            #    matrixStringifiedObject="${matrixStringifiedObject}'{"build-dir":"app2","app-dir":"app/"},'
+            #  elif [ "$i" == "app2" ]; then
+            #    matrixStringifiedObject="${matrixStringifiedObject}'{"build-dir":"app3","app-dir":""},'
+            #  fi
+            #fi
           done
           matrixStringifiedObject="${matrixStringifiedObject}"']}'
 
