print status

diff --git a/.github/workflows/dh.yml b/.github/workflows/dh.yml
--- a/.github/workflows/dh.yml
+++ b/.github/workflows/dh.yml
@@ -39,21 +39,9 @@ jobs:
       uses: lots0logs/gh-action-get-changed-files@2.1.4
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
-    - id: files
-      uses: jitterbit/get-changed-files@v1
-    - run: |
-        for changed_file in ${{ steps.files.outputs.all }}; do
-          echo "Do something with this ${changed_file}."
-        done
     - name: read file
       id: set_var
       run: |
-        echo "===="
-        git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
-        echo "===="
-
-        echo "===="
-
         content=`cat ${HOME}/files.json`
         content="${content//'%'/''}"
         content="${content//$'\n'/''}"
@@ -65,7 +53,7 @@ jobs:
         #content="${content//$'\r'/'%0D'}"
         echo "content: $content"
 
-        output=$(grep "github1" ${HOME}/files.json || echo "missing" )
+        output=$(grep 'github' ${HOME}/files.json || echo "missing" )
         if [ "$output" != "missing" ]; then
           output="found"
         fi
